# Generated by Django 3.2.21 on 2023-09-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_desc', models.TextField(max_length=254)),
                ('proj_link', models.URLField()),
                ('repo_link', models.URLField()),
                ('proj_pic', models.ImageField(upload_to='')),
                ('members', models.ManyToManyField(to='project_app.User')),
            ],
        ),
    ]
