# Generated by Django 3.2.21 on 2023-10-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='lists',
        ),
    ]
