# Generated by Django 3.2.21 on 2023-09-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('card_desc', models.TextField(max_length=254)),
                ('card_color', models.CharField(max_length=20)),
                ('assignees', models.ManyToManyField(to='project_app.User')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.lists')),
            ],
        ),
    ]
