# Generated by Django 3.2.21 on 2023-09-25 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_desc', models.TextField(max_length=200)),
                ('time', models.TimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.cards')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.cards')),
            ],
        ),
    ]
